name: RGCNExplainer
channels:
  - defaults
  - anaconda
  - conda-forge  # You can add additional channels here
dependencies:
  - rdflib=6.2.0
  - pytorch_revgrad=0.2.0
  - rdflib-jsonld=0.6.2
  - torch-geometric=2.3.0
  - wget=3.2
  - networkx=3.0
  - wandb=0.15.4
  - torch=1.12.1
  - matplotlib=3.6.3
  - fire=0.5.0
