wandb_version: 1

pred:
  desc: null
  value: 1
size:
  desc: null
  value: -10
feat_size:
  desc: null
  value: 1.0
ent:
  desc: null
  value: 1
feat_ent:
  desc: null
  value: 0.1
grad:
  desc: null
  value: 1
lap:
  desc: null
  value: 1.0
size_num:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.5
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683022103.840152
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 77
      2:
      - 1
      - 41
      - 49
      - 55
      - 77
      3:
      - 16
      - 23
      - 24
      4: 3.9.12
      5: 0.15.0
      8:
      - 5
