wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682698620.631066
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 77
      2:
      - 1
      - 41
      - 49
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.9.12
      5: 0.15.0
      8:
      - 5
