#!/bin/bash
#SBATCH --job-name=explain_sweep
#SBATCH --time=4:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --mem=164000M
#SBATCH --gpus-per-task=4
#SBATCH --output=explain_sweep

python3 mainR_explainer.py
