#!/bin/bash
#SBATCH --job-name=rgcn_expl_aifb
#SBATCH --time=4:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --mem=164000M
#SBATCH --gpus-per-task=4
#SBATCH --output=rgcn_expl_aifb

python3 r.py
#python3 rgcn_torch.py
