#!/bin/bash
#SBATCH --job-name=train_mdgenre
#SBATCH --time=4:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --mem=24000M
#SBATCH --gpus-per-task=4
#SBATCH --output=train_mdgenre

python3 rgcn_model_main.py
